services:
  - name: postgres
    envVars:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      PGDATA: /data/postgres
    volumes:
      - name: postgres
        path: /data/postgres
    ports:
      - 5432
    healthCheckPath: /health
    startCommand: ["docker-entrypoint.sh", "postgres"]

  - name: pgadmin
    envVars:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-root@admin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-root}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - name: pgadmin
        path: /var/lib/pgadmin
    ports:
      - 80
    healthCheckPath: /status
    startCommand: ["./entrypoint.sh"]

  - name: nestjs
    envVars:
      DB_HOST: ${DB_HOST} 
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      APP_PORT: ${APP_PORT}
      APP_OAUTH2_ENABLED: ${APP_OAUTH2_ENABLED}
      APP_MOCK_42_USERS: ${APP_MOCK_42_USERS}
      APP_OAUTH2_CLIENT_ID: ${APP_OAUTH2_CLIENT_ID}
      APP_OAUTH2_CLIENT_SECRET: ${APP_OAUTH2_CLIENT_SECRET}
      APP_OAUTH2_CALLBACK_URL: ${APP_OAUTH2_CALLBACK_URL}
      APP_OAUTH2_REDIRECT: ${APP_OAUTH2_REDIRECT}
      APP_SESSION_ID: ${APP_SESSION_ID}
      APP_SESSION_SECRET: ${APP_SESSION_SECRET}
      APP_SESSION_COOKIE_MAX_AGE: ${APP_SESSION_COOKIE_MAX_AGE}
      APP_SESSION_CLEANUP_LIMIT: ${APP_SESSION_CLEANUP_LIMIT}
      APP_CORS_ORIGIN: ${APP_CORS_ORIGIN}
      APP_TWO_FACTOR_AUTHENTICATION_NAME: ${APP_TWO_FACTOR_AUTHENTICATION_NAME}
    ports:
      - 3000
    healthCheckPath: /
    startCommand: ["npm", "start"]

  - name: nestjs-migrate
    envVars:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    healthCheckPath: /
    startCommand: ["npm", "run", "migration:run"]

  - name: svelte
    ports:
      - 3001
    healthCheckPath: /
    startCommand: ["npm", "start"]

volumes:
  - name: postgres
  - name: pgadmin
