services:
  - type: postgres
    name: postgres_db
    plan: free
    database: postgres
    username: ${POSTGRES_USER:-root}
    password: ${POSTGRES_PASSWORD:-root}

  - type: pgadmin
    name: pgadmin
    plan: free
    database_url: postgres://${POSTGRES_USER:-root}:${POSTGRES_PASSWORD:-root}@postgres:5432/postgres
    email: ${PGADMIN_DEFAULT_EMAIL:-root@admin.org}
    password: ${PGADMIN_DEFAULT_PASSWORD:-root}

  - type: web
    name: nestjs
    plan: free
    ports:
      - 3000
    buildCommand:
      - npm
      - install
    command:
      - npm
      - start
    environment:
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: postgres
      APP_PORT: 3000

  - type: web
    name: nestjs-migrate
    plan: free
    ports:
      - 80
    buildCommand:
      - npm
      - install
    command:
      - npm
      - run
      - migration:run
    environment:
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: postgres

  - type: web
    name: svelte
    plan: free
    ports:
      - 3001
    buildCommand:
      - npm
      - install
    command:
      - npm
      - start